<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends \Doctrine\ORM\EntityRepository
{    
    // Search cats or dogs
    public function whichTypeOfAnimal(QueryBuilder $qb, $animalType)
    {
        $qb
            ->innerJoin('a.breed', 'b')
            ->addSelect('b')
            ->innerJoin('b.type', 't')
            ->andWhere('t.name = :name')
            ->setParameter('name', $animalType)
        ;
    }
    
    // To manage animals list in admin, dependind on the last state (state with currentState = true)
    public function animalsListDependingOnLastState($animalType, $state)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.animalStates','ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 's')
            ->addSelect('s')
            ->andWhere('s.type = :type AND ls.currentState = true')
            ->setParameter('type', $state)
        ;

        $this->whichTypeOfAnimal($qb, $animalType);

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function animalsToAdoptList($animalType)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.animalStates','ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 's')
            ->addSelect('s')
            ->andWhere('s.type = :type')
            ->setParameter('type', 'adoptable')
            ->andWhere('s.type != :otherType')
            ->setParameter('otherType', 'adopté')
        ;

        $this->whichTypeOfAnimal($qb, $animalType);

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function animalsAlmostAdoptedList($animalType)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.animalStates','ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 's')
            ->addSelect('s')
            ->andWhere('s.type = :type')
            ->setParameter('type', 'réservé')
            ->andWhere('s.type != :otherType')
            ->setParameter('otherType', 'adopté')
        ;

        $this->whichTypeOfAnimal($qb, $animalType);

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    
    public function animalsNotToAdoptList($animalType, $state)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->innerJoin('a.animalStates','ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 's')
            ->addSelect('s')
            ->andWhere('s.type = :type')
            ->setParameter('type', $state)
        ;

        $this->whichTypeOfAnimal($qb, $animalType);

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    
    // To manage host families, search animals without host family
    public function getAnimalsAlone() 
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb
            ->andWhere('a.user is NULL')
            ->innerJoin('a.animalStates', 'ls')
            ->addSelect('ls')
            ->andWhere('ls.currentState = true')
            ->innerJoin('ls.state', 's')
            ->addSelect('s')
            ->andWhere('s.type = :type OR s.type = :secondType OR s.type= :thirdType')
            ->setParameter('type', 'adoptable')
            ->setParameter('secondType', 'réservé')
            ->setParameter('thirdType', 'trouvé')
        ;
        
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    
    // In order to paginate all the animals adopted by year
    public function getAdoptedAnimalsByYear($year) 
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb
            ->innerJoin('a.animalStates', 'ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 'st')
            ->addSelect('st')
            ->andWhere('st.type = :type')
            ->setParameter('type', 'adopté')
            ->andWhere('SUBSTRING(ls.date, 1, 4) = :year')
            ->setParameter('year', $year)
            ->orderBy('ls.date', 'DESC')
        ;
        
        return $qb
            ->getQuery()
            ->getResult()
        ;   
    }
    
    // In order to paginate all the animals adopted by year
    public function getTheYearOfTheFirstAdoption()
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb 
            ->innerJoin('a.animalStates', 'ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 'st')
            ->addSelect('st')
            ->andWhere('st.type = :type')
            ->setParameter('type', 'adopté')
            ->orderBy('ls.date', 'ASC')
            ->select('SUBSTRING(ls.date, 1, 4)')
            ->setMaxResults(1)
        ;
        
        return $qb
            ->getQuery()
            ->getOneOrNullResult()
        ;  
    }
    
    // In order to paginate all the animals adopted by year
    public function getTheYearOfTheLastAdoption()
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb
            ->innerJoin('a.animalStates', 'ls')
            ->addSelect('ls')
            ->innerJoin('ls.state', 'st')
            ->addSelect('st')
            ->andWhere('st.type = :type')
            ->setParameter('type', 'adopté')
            ->orderBy('ls.date', 'DESC')
            ->select('SUBSTRING(ls.date, 1, 4)')
            ->setMaxResults(1)
        ;
        
        return $qb
            ->getQuery()
            ->getOneOrNullResult()
        ;  
    }
}
