<?php

namespace AppBundle\Repository;

/**
 * AnimalStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalStateRepository extends \Doctrine\ORM\EntityRepository
{
}
