<?php

namespace AppBundle\Repository;

/**
 * AnimalStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalStateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastState($animalId) 
    {
        $qb = $this->createQueryBuilder('a');
        
        $qb 
            ->innerJoin('a.animal', 'l')
            ->addSelect('l')
            ->andWhere('l.id = :id')
            ->setParameter('id', $animalId)
            ->orderBy('a.date', 'DESC')
            ->setMaxResults(1)
        ;
        
        return $qb
            ->getQuery()
            ->getSingleResult()
        ;
    }
}
