<?php

namespace AppBundle\Repository;

/**
 * NotenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
     public function findNotesbyObject($object, $id)
    {
        
        $qb = $this->createQueryBuilder('n');
        
        $join = 'n.' . $object;
          
        $qb
            ->innerJoin($join,'ob')
            ->addSelect('ob')
            ->andWhere('ob.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
        
    }
}
