<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPagesByCategory($categoryId)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->innerJoin('p.category','c')
            ->addSelect('c')
            ->andWhere('c.id = :id')
            ->setParameter('id', $categoryId)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function getPublishedPagesByCategory($categoryName) 
    {
        $qb = $this->createQueryBuilder('p');
        
        $qb 
            ->innerJoin('p.category','c')
            ->addSelect('c')
            ->andWhere('c.name = :name')
            ->setParameter('name', $categoryName)
            ->andWhere('p.published = true')
            
        ;
        
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}