<?php

namespace AppBundle\Repository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEventPublications()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->andWhere('p.event IS NOT NULL')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    
    public function findDefaultPublications()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->innerJoin('p.animalState', 'pas')
            ->addSelect('pas')
            ->andWhere('pas.id IS NULL')
            ->andWhere('p.event IS NULL')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
