<?php

namespace AppBundle\Repository;

/**
 * TypeIdentificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeIdentificationRepository extends \Doctrine\ORM\EntityRepository
{
}
