<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByEmailOrPseudo($identifier)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->andWhere(
                $qb->expr()->orX(
                    'u.userPseudo = :identifier', 'u.email = :identifier'
                )
            )
            ->setParameter('identifier', $identifier);
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
    
    public function getUsersWithSpecificRole($role)
    {
        $qb = $this->createQueryBuilder('u');
        
        $qb
            ->andWhere('u.roles LIKE :role')
            ->setParameter('role', '%"'.$role.'"%')
            ->orderBy('u.userPseudo', 'ASC')
        ;
        
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
